### ISSUE TITLE
Support for embedded artifacts

### ISSUE THREAD

**Issue by srs** [TomDmitriev/gradle-bundle-plugin#2]
Hi.

I would really like to use this plugin, but need to be able to embed artifacts. Have created a similar plugin that does the job, but do you have any future plans for your plugin?

I could invest some time to get to know your code and create the posibility to embed artifacts like I did in our company internal plugin. It works pretty automatic (from the user's perspective) - just mark dependencies that needs to be embedded in scope 'embeddedCompile' like this:

    dependencies {
        embeddedCompile 'commons-lang:commons-lang:2.4'
    }

    bundle {
        instruction '-exportcontents', 'org.apache.commons.lang.*'
    }

So, what do you think?

**Comment by TomDmitriev** [comment]
I'm closing the issue.
