### ISSUE TITLE
"up to date" checks fail for the jar operation

### ISSUE THREAD

**Issue by rotty3000** [TomDmitriev/gradle-bundle-plugin#26]
the jar task is always re-executed

**Comment by TomDmitriev** [comment]
Sorry, I haven't been availalbe during Christam holidays. How could I reproduce the issue? Note, there are a couple of integration tests checking that the jar task is not executed if manifest file has not been changed (see @Issue(1)).

**Comment by rotty3000** [comment]
Not a problem! Hope you had a great holiday ☺

To reproduce, simply note during the build that gradle never emits a message indicating assemble stage was up to date.

**Comment by TomDmitriev** [comment]
Hmmm. I can't reproduce it on a simple project I set up. Perhaps, a failing integ test would be helpful.
