### ISSUE TITLE
using packageinfo files to track package versions results in "split-package" warnings

### ISSUE THREAD

**Issue by rotty3000** [TomDmitriev/gradle-bundle-plugin#27]
add a `packageinfo` text file into any exported package (note you must place this in src/main/resources in order for it to be included into the resulting jar)

e.g.`src/main/resources/the/versioned/package/packageinfo`

Upon building you should get a warning something like:

```
...
:jar
[Split package, multiple jars provide the same package:the/versioned/package
Use Import/Export Package directive -split-package:=(merge-first|merge-last|error|first) to get rid of this warning
Package found in   [Jar:main, Jar:main]
Class path         [Jar:main, Jar:main]]
...
```

If there were some other way to apply the packageinfo files directly in the src that would be great solution but it doesn't seem to work. the files are ignored and never included in the jar.

**Comment by zline** [comment]
The same problem occurs when placing resources with directory structure similar to the package layout, e.g. locale-dependent translation files:
`src/main/java/org/example/Test.java` and `src/main/resources/org/example/Test_ru.properties`

**Comment by zline** [comment]
@TomDmitriev could you please explain the logic behind JarBuilder.resources field?
I see that both compiled classes and resource files get added to this field. Later, this field added to classpath (causing split-package in some cases like this) and used in Include-Resource. Should't compiled classes and resource files be treated separately?

**Comment by tonit** [comment]
@TomDmitriev any news on this? We are facing very similar issues. I'd also agree with @zline reasoning.
