### ISSUE TITLE
How to handle conflicting jar specifications

### ISSUE THREAD

**Issue by jwgish** [TomDmitriev/gradle-bundle-plugin#3]
I've just started using this and am wondering how to handle the following situation. We have a number of instances where in a project's build.gradle we do something like this:

jar { 
from (zipTree(file('foo-stuff.jar'))) { 
exclude 'bar/**' 
exclude 'META-INF/INDEX.LIST' 
exclude 'META-INF/MANIFEST.MF' 
} 
}

However, when I do this to a project where the apply plugin: 'bundle' has been done, all I get in the jar is the manifest generated by bnd. How do I handle this?

Thanks, 
Jim

**Comment by TomDmitriev** [comment]
I suppose it can be closed now.
