### ISSUE TITLE
Large memory usage

### ISSUE THREAD

**Issue by mbelling** [TomDmitriev/gradle-bundle-plugin#37]
We have a project with a lot of subprojects that I am trying to convert to using the gradle-bundle-plugin.  The issue I am coming across is that a gradle build with this plugin will take up to ~4GB of memory and retain that after the build is finished in the daemon.  When I profiled using Yourkit, I found that there are a lot of aQute.bnd.osgi.ZipResource left behind, which ends up taking up most of that memory.  

I am not familiar enough with how this plugin works internally, nor with the internals of BND, but one or the other is leaving behind a lot of stuff in memory, and that will prevent us from converting to this plugin.

**Comment by TomDmitriev** [comment]
Although I have not reproduced the issue there was apparently a problem in the code which might have caused the memory leak. The problem is fixed in the latest release, 0.6.4. Could you please grab it and verify whether the issue has been resolved?

**Comment by mbelling** [comment]
I'll see if I can try it out today, thanks for the update.

**Comment by mbelling** [comment]
It did not fix the issue for me.  I'm going to create a small test example and see if I can reproduce in a simple project.

**Comment by mbelling** [comment]
Upon further investigation, I determined that this is due to another unrelated plugin.  Closing.
