### ISSUE TITLE
Exclude transitive dependencies in the manifest

### ISSUE THREAD

**Issue by mjgp2** [TomDmitriev/gradle-bundle-plugin#38]
I would like to be using wildcards for the `Import-Package` declaration, but at the moment it pulls in all the packages from the transitive dependencies that match the pattern also.

The point of doing this is to reduce friction for developers so that they don't need to add or remove the package somewhere else.

There's a feature in the bnd maven plugin `excludeDependencies comma-separated list of dependency artifactIds to exclude from the classpath passed to Bnd, use "true" to exclude everything` which seems to match up perhaps?

Any feedback appreciated :)

**Comment by TomDmitriev** [comment]
Will be implemented in v0.7.

**Comment by mjgp2** [comment]
Brilliant, thanks :)

**Comment by TomDmitriev** [comment]
Updated README with the instructions.
