### ISSUE TITLE
How to nest jar's into bundle lib folder?

### ISSUE THREAD

**Issue by paulvi** [TomDmitriev/gradle-bundle-plugin#54]
How to nest jar's into bundle lib folder?

**Comment by TomDmitriev** [comment]
[Include-Resource](http://www.aqute.biz/Bnd/Format#include-resource) is probably what you need.

**Comment by paulvi** [comment]
Exactly.

 `Include-Resource:   lib/=lib/, META-INF/=META-INF/`

however there is still open bug https://issues.gradle.org/browse/GRADLE-1107 "OSGi instruction Include-Resource not working"

**Comment by rotty3000** [comment]
I don't believe that bug report is relevant to this plugin. Are you using
the built in gradle OSGi plugin? Or are you using Tom's (this repo)?

**Comment by paulvi** [comment]
@rotty3000 yes sure, GRADLE-1107 is for  built-in Gradle OSGi plugin only.

**Comment by TomDmitriev** [comment]
I'm closing the issue then.
