### ISSUE TITLE
Add entry at http://bnd.bndtools.org/chapters/700-tools.html

### ISSUE THREAD

**Issue by paulvi** [TomDmitriev/gradle-bundle-plugin#55]
Please consider to add an entry for this plugin at http://bnd.bndtools.org/chapters/700-tools.html

Just add .md file at https://github.com/bndtools/bnd.manual/tree/gh-pages/_tools
(Hint: use GitHub <kbd>New File</kbd> button)

**Comment by TomDmitriev** [comment]
https://github.com/bndtools/bnd.manual/pull/31#event-617153335
Done.
