### ISSUE TITLE
configurations.compile will not include 'compileOnly' (2.12) dependencies 

### ISSUE THREAD

**Issue by paulvi** [TomDmitriev/gradle-bundle-plugin#56]
With Gradle 2.12

https://docs.gradle.org/2.12/release-notes#java-plugin-%27compile%27-configuration-no-longer-represents-all-compile-time-dependencies

> As a result of the addition of compile only dependencies, references to configurations.compile no longer accurately represent the compile classpath used to build a given source set, as this will not include 'compileOnly' dependencies. When needing a reference to a source set's compile classpath, configurations.compileClasspath or configurations.testCompileClasspath should instead be used to reference the production or test classpaths, respectively.

Can this effect this plugin?

**Comment by TomDmitriev** [comment]
It does affect it in the sense that compileOnly dependencies will not be
included to the classpath passed to Bnd.

On 11 April 2016 at 12:13, Paul Verest <notifications@github.com> wrote:

> With Gradle 2.12
>
>
> https://docs.gradle.org/2.12/release-notes#java-plugin-%27compile%27-configuration-no-longer-represents-all-compile-time-dependencies
>
> As a result of the addition of compile only dependencies, references to
> configurations.compile no longer accurately represent the compile classpath
> used to build a given source set, as this will not include 'compileOnly'
> dependencies. When needing a reference to a source set's compile classpath,
> configurations.compileClasspath or configurations.testCompileClasspath
> should instead be used to reference the production or test classpaths,
> respectively.
>
> Can this effect this plugin?
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/TomDmitriev/gradle-bundle-plugin/issues/56>
>



-- 
Yours sincerely,
Artyom Dmitriev
