### ISSUE TITLE
Semver-incompatibility

### ISSUE THREAD

**Issue by yuchi** [TomDmitriev/gradle-bundle-plugin#64]
Looks like there are issues when the Bundle-Version is specified by using the semver form `M.m.b+timestamp`, more precisely by having in the *bnd* file the form `1.0.0+${tstamp}`.

Sorry for the horribly brief description. If you need more details I could look into it better.

**Comment by rotty3000** [comment]
hey @yuchi having a `+` as the separator between the micro and qualifier is not supported by OSGi. The only legal separator is `.`

i.e. `1.0.0.${tstamp}`

**Comment by yuchi** [comment]
That's what I feared. Then why is it the standard value in the `bnd.bnd` file built by `blade create`. Gonna investigate more. Thanks @rotty3000

**Comment by yuchi** [comment]
My bad, it's me that changed the form into the semver complaint one.
